### ISSUE TITLE
Android 4.x へのバックポート

### ISSUE THREAD

**Issue by tateisu** [tateisu/FADownloader#1]
FADownloader をAndroid 4.x にバックポートする場合
- ACTION_OPEN_DOCUMENT_TREEがないからフォルダ選択画面をアプリ側で用意
- DocumentFileクラスの代わりにFileクラスを使う
- Rtlサポートがないのでレイアウト指定のStart,EndをLeft,Rightに書き換える
- Networkクラスがないので通信状態の確認を古いAPIに置き換える
- KitKatではSDカードへのアクセスに制約があるが、どうしようもないので割り切る
てな感じになるかな。難しくはないけど地味な作業が多め

**Comment by wawyam** [comment]
ありがとうございます。
こちらを参考にがんばってみます！

**Comment by tateisu** [comment]
https://github.com/tateisu/FADownloader/releases/tag/v1.4
v1.4でとりあえず起動するようにはなったけど、テスト時間は取れないなあ…

**Comment by wawyam** [comment]
ありがとうございます！
こんな後ろ向きな事に手間を取らせてしまい申し訳ない限りです。
実機検証とログを見るくらいしかできませんがテストがんばります。

**Comment by wawyam** [comment]
21時頃取得したソースをビルドし、4.3のNote3で試したところ5.0同様に動作しているようです。
まだまだテストが必要ではありますが、本当にありがとうございました。

もうお気づきだとは思いますがクラスWifiTrackerのファイル名がWiFiTracker.javaとなっており修正が必要ですね。

**Comment by tateisu** [comment]
＞WifiTrackerのファイル名がWiFiTracker.java
![filename](https://cloud.githubusercontent.com/assets/333944/23663590/5d85e0dc-0396-11e7-8f6a-546cd7872c3e.jpg)
ウチの環境だと同じに見えてますが、Github上でみると確かに違ってる！ Github上でリネームしてコミットしておきました。

4.0のSH-01DでWi－Fiの電波を掴めなさすぎて動かないとかPlayサービスと連動できないとかがあったかなー

**Comment by tateisu** [comment]
特にできることもなさそうなので一旦クローズ。問題があればまた別課題で
