### ISSUE TITLE
転送完了時の通知

### ISSUE THREAD

**Issue by tateisu** [tateisu/FADownloader#10]
＞キューが0になった時点でバイブレーションする機能(設定でON/OFF可)

- バイブレーションや音に限らず、システム通知を出した方が良さそう
- 通知をタップする前に別のファイルの転送を開始したら通知も消しちゃう？

**Comment by wawyam** [comment]
機能の趣旨からは転送開始で通知を消した方が一目で転送完了が確認できてよいように感じます。
Widgetになればオシャレではありますが、表示したい情報はそれほど多くはないですしね。

**Comment by tateisu** [comment]
実装しました。通知に付随する音、バイブ、LEDの挙動は端末側の通知設定に従うようにしています

**Comment by wawyam** [comment]
お疲れ様です。動作を確認しました。
すみません、未転送ファイルがある状態でさらに撮影するとキューが追加されると思い込んでいました。
転送開始以降、(転送が完了して)最初のファイルスキャン完了時に更新されていない場合に通知、というのはいかがでしょうか。

また、通知の設定はアプリケーション管理から行うようですが、一般ユーザーはすぐにわからない可能性が高い気がします。
FAD内から設定するのが面倒でしたらデフォルトOFFの方がよいかもしれません。

追記：5以降の通知設定は少し親切になっているようですね。

**Comment by tateisu** [comment]
「ファイルをダウンロードした場合、待機時間にかかわらずもう一度ファイルスキャンをして更新がないとわかってから通知を出す」
ということでしょうか。ONCEとREPEATで挙動を変えたり待機条件を変えたり潜伏ダウンロード数を覚えさせたりしました

**Comment by tateisu** [comment]
あとウィジェットも作ってみましたが正直使いどころがよくわかりません

**Comment by wawyam** [comment]
確認しました。
通知のタイミングは私の理想通りです。ありがとうございました。
想定していたより手間がかかったようで申し訳ありませんでした(ONCEでの動作を失念していました)。

ウィジェットの件は別issueとさせていただきます。

**Comment by wawyam** [comment]
本日撮影してきた感じでは問題ないと思われます。
以前より画面を確認することが減りました。
感謝です。
