### ISSUE TITLE
ログのクリップボード転送

### ISSUE THREAD

**Issue by wawyam** [tateisu/FADownloader#11]
ほとんどのユーザーには不要とは思いますが、ログをクリップボードに送る機能を実装していただけませんでしょうか^^;

**Comment by tateisu** [comment]
ログを他アプリに送信する機能を追加しました。
DropboxやGoogleDriveに送ったり、Gmailの添付ファイルにしたりできます
問題なさそうならIssueをクローズしてください

**Comment by wawyam** [comment]
要望以上の作りこみ、すばらしいです。
ありがとうございました！
