### ISSUE TITLE
ウィジェット機能について

### ISSUE THREAD

**Issue by wawyam** [tateisu/FADownloader#14]
私が当初FADに望んでいた機能は100%実装され満足していますのでネタ程度に聞き流してくださいね。

私の考えるウィジェットは大まかに以下のイメージとなります。

![widget](https://cloud.githubusercontent.com/assets/26176019/24198118/c80d7d40-0f47-11e7-885c-717fbf4e8244.jpg)

4x1を想定しています。
ステータス情報は現FADのメッセージ欄と同じ内容でもよいかと思います。
WiFiアイコンっぽいのはテザリングのON/OFF切り替え機能となります。
(現在別アプリ「テザリングON/OFF」で行っています）

**Comment by tateisu** [comment]
テザリング前提のターゲットタイプで「テザリング半強制」をやるのは考えてますが
手動でテザリングON/OFFするボタンはこのアプリでやる必要がない気がします
私はNotification Toggle派です。いちいちホームに戻らなくて良いのが利点

提案された表示要素の中で一番厄介なのがステータス情報です。
頻繁に情報を更新するAppWidgetは受動的に表示更新できるのは30分に1回までで、
それより短い間隔で更新したい場合はアプリ側から更新を行うプッシュ動作になります。
この場合アプリで考慮できるのはスクリーンOFF時に更新を行わない程度までで、
現在表示されている画面がAppWidgetHostかどうかはわかりません。

FADのサービス起動中に出る通知のテキストが妙に素っ気ないのも、
通知を更新する頻度を下げるためだったりします
(通知を出すこと自体はstartForegroundのために必須)

あと地味に怖いのがウィジェット表示のカスタマイズ機能を要求されることだったり…
画面カスタマイズする勢に関わるとキリがないのは別アプリで体験済み

…とまあ工数を結構使う割に、できることが増えるわけでもないので
アプリ画面を縮小したようなウィジェットを提供することには消極的です

**Comment by wawyam** [comment]
なるほど、ステータス情報の更新が厄介というのは予想外でした。
ウィジェットはあまり即応性が無いのですね。いろいろ納得です。
