### ISSUE TITLE
選択自動転送機能

### ISSUE THREAD

**Issue by wawyam** [tateisu/FADownloader#15]
FlashAirのファイル取得APIで属性(読み取り専用)も取得しているのですね。
これを利用してカメラでプロテクトした画像のみ自動転送する機能などいかがでしょうか。
EyeFiの選択転送と同様のしくみですが、選択転送派も少なからずおられると思われます。
私はPENTAX(WiFi無し)なので連射とは無縁で全転送派ですが。。

**Comment by tateisu** [comment]
実装しました。

**Comment by wawyam** [comment]
多くは無いですが動作確認しました。
ありがとうございました。
