### ISSUE TITLE
転送画像のギャラリー反映

### ISSUE THREAD

**Issue by wawyam** [tateisu/FADownloader#16]
転送された画像がなかなか(再起動するまで？)ギャラリーに反映されないのは自分の環境が悪いのかと思っていたのですが、以下の記事を見つけました。

https://teratail.com/questions/52150
http://librastudio.hatenablog.com/entry/2013/08/01/010357

すでに何らかの対策をされているのでしたらすみませんです。

**Comment by tateisu** [comment]
QuickPicビューアだとMediaStoreへの登録を気にしなくても大丈夫
という理由で今まで気にしてなかったんですが
クラウド同期アプリ等がMediaStoreの新着チェックを行う場合などを考えると
MediaScannerへの登録は必要そうですね…

**Comment by tateisu** [comment]
実装しておきました

**Comment by wawyam** [comment]
お疲れ様です。

カメラに20枚程度撮り溜めた状態からSTAモードのREPEATで一度に取得し、(google)フォト、ギャラリーで確認したところ、数枚に1枚くらいの割合で破損画像(アイコン)のようなものが表示されます。
(撮影した画像は全て転送、表示されていますが破損アイコンがところどころ挿入されている状態)
4.3、5で同様の状況で、再起動により破損アイコンは消えるようです。

恐れ入りますがご確認いただけますでしょうか。

**Comment by tateisu** [comment]
JPEG20枚、位置情報バランス で転送完了後に確認

+ Nexus 5X(7.1.1) : Googleフォト問題なし/ ギャラリーはプリインされていない
+ HTL22 (4.4.2) : Googleフォト問題なし / ギャラリー(HTC風)問題なし
+ Galaxy Nexus (4.3) : Googleフォト問題なし / ギャラリー問題なし
+ Aubee elm. (5.1) ギャラリーでフォルダ中に画像が23枚。3枚の破損サムネイルは位置情報付与の際に作成した一時ファイルを指していた

再現したので色々と対策しました

**Comment by wawyam** [comment]
意外とレアケースだったのですね。
4.3、5で破損サムネイルが出現しなくなったことを確認しました。
ご対応ありがとうございました！

**Comment by wawyam** [comment]
本日300枚弱撮影し、破損サムネイル、抜け等がないことを確認しました(4.3)。
