### ISSUE TITLE
Wi-Fi AP を安定させる方法

### ISSUE THREAD

**Issue by tateisu** [tateisu/FADownloader#2]
ユーザ目線だと
+ 機内モードにしてからWi-Fiを有効にすると、勝手にモバイル回線に切り替わるのを防止できる
+ Wi-Fi APの設定で静的IPを使うとDHCPのIPアドレス払い出しの時間を省略できる。FlashAir は192.168.0.1固定なのでゲートウェイとDNSをそれにして、スマホ端末は192.168.0.(2～254) にする

アプリとしてはWiFiManagerを使って何かできないか検討してみたい
- SSIDとパスワードをアプリ側で覚えて、AP一覧が更新された時にSSIDがあれば強制的に接続させる等
参考：http://blog.dtdweb.com/2013/03/08/android-wifi-network/

**Comment by tateisu** [comment]
Wi-Fi AP 強制機能を実装しました。
https://github.com/tateisu/FADownloader/releases/tag/v1.3

**Comment by wawyam** [comment]
以下の機種でWi-Fi AP 強制機能を試してみました。(Ver1.5)
1:SCL22(5.0)
2:SCL22(4.3)
3:KYY21(4.2.2)
4:SC-05D(4.0.4)

1は快適に動作しますが、4.xはFlashAir切断後の復帰が不安定ですね。
FlashAir切断後に数分スリープさせると復活しているような感じです。
(ステルスSSIDだとWiFi一覧画面からタップしても「接続」ボタンが表示されない)

個人的には必須機能ではありませんがご報告まで。

**Comment by tateisu** [comment]
ステルスSSIDだとスキャンしてAPの存在を確認することができません。
APを確認できなくても自動で接続しに行くのはやりすぎだと思うので、ステルスSSIDだとWi-Fi半強制機能は動作対象外という扱いにした方がよさそうです

**Comment by tateisu** [comment]
特にできることがなさそうなので一旦クローズ。不具合や不適切な挙動が指摘されたらまた別課題で…
