### ISSUE TITLE
取得ファイル一覧

### ISSUE THREAD

**Issue by wawyam** [tateisu/FADownloader#3]
あつかましい要望となりますが、ログとは別に取得ファイル一覧タブを追加し、メイン画面とするのはいかがでしょうか。
ファイル名、ステータス(取得済、未取得、エラー等)を表示し、ログ同様に任意に全クリア可能とするイメージです。
タップで関連付けした外部ビューアで画像表示できるといいですね。

ファイル取得系のログを別の色にするだけでもご検討いただければと思います。

**Comment by tateisu** [comment]
ファイル更新履歴は良いかもしれませんね。シェアとかにも便利そうだし

**Comment by tateisu** [comment]
適当に実装してpushしておきました

**Comment by tateisu** [comment]
試してみたら、SDカードやUSBメモリなどのnon-primary storageを開けない画像ビューアがありました。QuickPic等… primary storage にコピーしてから開かせる等した方が良いかもしれません

**Comment by tateisu** [comment]
どれをメイン画面にするかより、最後に開いていたタブを覚える方を検討した方がよさそう

**Comment by wawyam** [comment]
仕事が早いですね！ありがとうございます！

さっそく試してみたところ、5.0では想定通りビューワを選択して表示できましたが、 4.3(Note3)ではいきなり「PDFを表示できません」でエラーとなり、4.0.4(Note1)では何も起こらない状態です。
5.0で表示可能な「フォト」が4.xにもインストールされているのですが、私の環境だけの問題かもしれません。

明細内容は
「ファイル名（パス無し）」「ステータス」（できれば色付け）
もしくは
「受信日時」
「ファイル名（パス無し）」
「ステータス」
くらいが視認性がよいように感じます。（他は「詳細」ボタン、長押しから「詳細」もしくはログで確認など・・）
一覧に未取得ファイルも表示されるといいですが、リスト取得毎に更新が必要になりそうですね。。

>最後に開いていたタブを覚える
そちらの方がよさそうですね。

**Comment by tateisu** [comment]
途中で中断したら未取得ファイルはいつ消すのか…って問題がありまして
履歴とキューを同じリストにするのはUI的によくないと思います。
試してみたら未取得時にファイルが追加されて、その後ダウンロードされたファイルが（時間順なので)リストの一番上に移動します。
キューだけのビューを作るのも考えましたが、あまり有用ではないだろうということで
かわりに状況表示の黒い部分に進捗率と残りファイル数、バイト数を記載しました。

履歴のリスト内の表示をシンプルにしました。サムネイル表示を追加しました。
リスト内の項目をタップするとダイアログが開き、詳細情報の確認とView,Sendを選べるようにしました。
view,sendはファイルを端末のダウンロードフォルダにコピーしてそれをIntentに指定するようにしました。
また、ファイル拡張子とMimeTypeMap APIでmime typeを適切に指定したintentを送るようにしました。

検討中ですが詳細情報にサムネイル、Av,Tv,ISO,Xv(露出補正)、機種名などを詳細に表示するのもアリかもしれません

悩んだのがEXIFの回転情報を使ってサムネイルを回転させるかどうかです。現在は回転させています。
しかしシェア先のアプリは自動回転に対応していないものがままあるため、シェア目的の一覧では自動回転させない方が良いのでは？とも思っています

**Comment by wawyam** [comment]
お疲れ様です。
ダウンロード履歴、すばらしいです。
サムネイル表示、フォントサイズ調整など期待を上回る仕上がりです。
ビューワ連携も4.3、4.0.4でも問題なく表示されることを確認しました。
転送された画像がビューワに反映されるタイミングが気まぐれなので助かります。
未取得ファイル表示については現在の信頼度であれば残りファイル数がわかれば十分です。
ありがとうございました^^

一点、ファイルを端末のダウンロードフォルダにコピーするのはnon-primary storageを開けない画像ビューアへの対策と思われますが、view,send後もファイルが残り、ビューワ(Note3の「ギャラリー」等)に出現してしまうので、直接表示/コピー表示を「設定」で選択可能としていただけるとありがたいです。

サムネイルを回転についても「設定」でユーザーに任せればよいかと考えます。

**Comment by tateisu** [comment]
設定を二つ追加しました。

non-primary storageのフォルダパスを取得する非公開APIを使うようになったので、そのAPIが使える端末でならコピー設定をオフにしてもQuickPicで開けるようになりました。Androidのソースをみると5.0から7.1まですべて大丈夫だとは思います。

**Comment by wawyam** [comment]
ほぼ理想のカタチになりました。ありがとうございました！
