### ISSUE TITLE
FlashAir STAモード

### ISSUE THREAD

**Issue by tateisu** [tateisu/FADownloader#8]
v1.8で行っていること

Target TypeでFlashAir STAモードが選ばれている場合の通信状況確認
1、サービス開始直後(初回)は待機しない。2回目以降は少し待機する。前回の確認でカードが見つかった場合は30秒、見つからなかった場合は3秒。
2、設定で指定したURLにIPアドレスらしきものが含まれるなら、FlashAirカードのHTTP APIをリクエストして応答があればカード確認完了。
3、/proc/net/arpを見てMACアドレスが00:00:00:00:00:00ではないIPアドレスがあれば、FlashAirカードのHTTP APIをリクエストして応答があればカード確認完了。ARPテーブルが長いと結構時間がかかるかも？
4、スマホのテザリング時のネットワークインタフェースのIPv4アドレスを取得。テザリングがOFFだとIPアドレスは見つからない。アドレスが見つかったらアドレスの末尾2～254の範囲に対してUDPパケットを投げる。FlashAirカードがテザリング接続されていれば、しばらく後に /proc/net/arp にFlashAirカードが見つかるはず

**Comment by tateisu** [comment]
…あれ、これだとテザリングじゃないWi-Fi接続があるときはARPテーブルにある範囲全部にHTTPリクエストを投げて結構時間がかかっちゃうんじゃないか。先にスマホのテザリング時のネットワークインタフェースのIPv4アドレスを取得して、ARPテーブルを確認するときにフィルタリングするべきだと思う

**Comment by tateisu** [comment]
1.8.1 で直します…

Target TypeでFlashAir STAモードが選ばれている場合の通信状況確認
1、サービス開始直後(初回)は待機しない。2回目以降は少し待機する。前回の確認でカードが見つかった場合は30秒、見つからなかった場合は3秒。
2、設定で指定したURLにIPアドレスらしきものが含まれるなら、FlashAirカードのHTTP APIをリクエストして応答があればカード確認完了。
3、スマホのテザリング時のネットワークインタフェースのIPv4アドレスを取得。テザリングがOFFだとIPアドレスは見つからない。エラー終了。
4、/proc/net/arpを見てMACアドレスが00:00:00:00:00:00ではない＆テザリング範囲のIPアドレスがあれば、FlashAirカードのHTTP APIをリクエストして応答があればカード確認完了。ARPテーブルが長いと結構時間がかかるかも？
5、テザリング範囲のアドレス（末尾2～254）に対してUDPパケットを投げる。FlashAirカードがテザリング接続されていれば、しばらく後に /proc/net/arp にFlashAirカードが見つかるはず。エラー終了

**Comment by tateisu** [comment]
直しました。
テザリングのIPアドレスを取得しようとしたら普通の無線LANのIPアドレスを拾ってしまうことがあったので、非公開APIでテザリングON/OFFの確認を行ってからテザリングのIPアドレスを取得するようにしました

**Comment by wawyam** [comment]
FlashAirに子機モードなんてあったんですね。

STAモードで数枚試してみたところイイ感じだったのですが、あるタイミングで1枚撮影して転送前にカメラOFFしたところ、カメラONで未転送画像が転送されたあと、以降撮影しても転送されない状態となりました。

ログは「sent UDP…」「checkFlashAirUrl…」のみが繰り返される状態でカメラのON/OFFでも状況は変わりませんでした(スマホ画面にはテザリング接続されたメッセージあり)。

FlashAirをAP設定に戻し、FADをAPモードで開始したところ、未転送の画像が全て転送されました。

まだ再現チェックもしておらず、たまたま＆オレ環かもしれませんがご報告まで。
端末は4.3(Note3)です。

**Comment by wawyam** [comment]
再度FlashAirをSTAに設定して同一環境で何度か試してみましたが再現しませんね。
ちゃんと転送が復活します。
しばらく様子を見てみます。お騒がせ失礼しました。

**Comment by tateisu** [comment]
checkFlashAirUrl... が出てるならアプリ側からのIPアドレス検出＋接続試行まではできてると思います。接続に失敗してる理由まではログに出してないので分かりません。もしConnection Timeout (単に接続に時間がかかりすぎている）とかなら状況により出たりでなかったりするかもしれません。5秒タイムアウトだと少し短すぎるのかもしれませんね

**Comment by tateisu** [comment]
もう一つの可能性としては、スマホ側のルーティングテーブルがテザリングを考慮したものに（一時的に？）なっていない場合です。これはスマホ側のテザリングをやり直す＆カードを再起動するという手順で解決するかもしれません。

**Comment by tateisu** [comment]
最新のコミットでSTAモードのタイムアウトを30秒にして、失敗時のログ出力も追加しておきました。

**Comment by wawyam** [comment]
調整ありがとうございます。

本日(3/19)400枚程度STAモードで撮影し、全ファイルが転送されたことを確認しました。
(スマホはテザリングタイムアウト無し、カメラはオートパワーオフ1分で放置)

途中一度だけ20枚ほどキューに溜まったことがありましたが、画面を見ながら何度かカメラをOFF/ONしたところ転送が再開されました。
ログを確認したところ最後(キューに溜まる直前)のファイル転送完了後「スレッド再作成 」が出現していないようです(それ以外に他の転送再開との有意な差は見つけられていません)。
次回は5.0で試してみます。

別issueにすべきかもですが、キューが0になった時点でバイブレーションする機能(設定でON/OFF可)があるとありがたいのですが、バッテリーへの影響は大きいでしょうか？

**Comment by tateisu** [comment]
はい、別Issueにしましょう

**Comment by tateisu** [comment]
スレッド終了と再作成にはそれぞれ理由があって、ログにそれも書かれるはずです

あと、裏技っぽいですがRepeat Interval を15秒未満にすると待機時にアラームを使わず「短い待機」を使うようになるので、スレッドが起きなくて困ることはなくなります。

コード的にはAlarmの使い方をもう少し見直してみます

**Comment by tateisu** [comment]
いくつか見直しましたが、根本的なところで言うとテザリング前提のモードにはアラーム待機自体必要ないんじゃないか…？ という気がします… テザリング中は端末のCPUはスリープしないので、普通にwait()でいいんじゃないだろうか…
